services:
  kong:
    image: kong:3.6
    container_name: cc-gateway
    ports:
      - "8000:8000"
      - "8001:8001"
      - "8443:8443"
    volumes:
      - ./config/kong.conf:/etc/kong/kong.conf.default:ro
      - ./config/kong.yaml:/etc/kong/kong.yaml:ro
    environment:
      - KONG_DATABASE=off
      - KONG_DECLARATIVE_CONFIG=/etc/kong/kong.yaml
    networks:
      - cloud-demo
    restart: unless-stopped
  
  logger:
    build: ./logger
    container_name: cc-logger
    ports:
      - "8080:8080"
    networks:
      - cloud-demo
    restart: unless-stopped
    depends_on:
      - db

  db:
    image: mongo
    container_name: cc-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    networks:
      - cloud-demo
  
  hello:
    build:
      context: ./hello-world
      dockerfile: Dockerfile
    container_name: hello
    expose:
      - "8000"
    networks:
      - cloud-demo
    restart: unless-stopped
  
  hello-copy:
    build:
      context: ./hello-world
      dockerfile: Dockerfile
    container_name: hello-copy
    expose:
      - "8000"
    networks:
      - cloud-demo
    restart: unless-stopped  

networks:
  cloud-demo:
    driver: bridge

