_format_version: "3.0"

upstreams:
  - name: hello-upstream
    algorithm: round-robin
    targets:
      - target: hello:8000 # Change to IP in cloud
      - target: hello-copy:8000 # Change to IP in cloud

services:
  - name: hello-service
    host: hello-upstream
    port: 8000
    routes:
      - name: hello-route
        paths:
          - /hello

plugins:
- name: http-log
  config:
    http_endpoint: http://localhost:8080/logs
    method: POST
    timeout: 1000
    keepalive: 1000
    flush_timeout: 2
    retry_count: 15
