_format_version: "3.0"

upstreams:
  - name: frontend-upstream
    algorithm: round-robin
    targets:
      - target: 172.24.0.136:80

  - name: inference-upstream
    algorithm: round-robin
    targets:
      - target: 172.24.0.9:8000

  - name: auth-upstream
    algorithm: round-robin
    targets:
      - target: 172.24.0.189:8080

services:
  - name: frontend-service
    host: frontend-upstream
    port: 80
    routes:
      - name: frontend-route
        paths:
          - /
  - name: inference-service
    host: inference-upstream
    port: 8000
    routes:
      - name: inference-route
        paths:
          - /api/v1/inference

  - name: auth-service
    host: auth-upstream
    port: 8080
    routes:
      - name: auth-route
        paths:
          - /api/v1/auth

plugins:
- name: http-log
  config:
    http_endpoint: http://172.24.0.130:8080/logs
    method: POST
    timeout: 1000
    keepalive: 1000
    flush_timeout: 2
    retry_count: 15
